### ISSUE TITLE
Справка по Slash командам и tree.sync()

### ISSUE THREAD

**Issue by issamansur** [oqo0/discord-badge#2]
Привет, вопросик: можно ссылочку на руководство/документацию, по которой была написана часть про slash команды и sync'а основного дерева команд? Фрагмент:

https://github.com/oqo0/discord-badge/blob/c28d2c0de08e76a53b034f6ee4840eecf31f9491/main.py#L35-L44

и
https://github.com/oqo0/discord-badge/blob/c28d2c0de08e76a53b034f6ee4840eecf31f9491/main.py#L70-L82
Просто пишу слэш команды, но хотел бы обойтись без реализации декоратора/переопределения

**Comment by oqo0** [comment]
Из примеров discord.py:
https://github.com/Rapptz/discord.py/blob/master/examples/app_commands/basic.py
